version: '2'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    hostname: zookeeper
    container_name: kafka-zookeeper
    ports:
        - '2181:2181'
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        KAFKA_OPTS: '-Djava.security.auth.login.config=/opt/confluentinc/kafka/config/zookeeper_jaas.conf'
    volumes:
        - ./kafka-setup/configs/zookeeper_jaas.conf:/opt/confluentinc/kafka/config/zookeeper_jaas.conf
  
  broker:
    image: 'confluentinc/cp-server:latest'
    hostname: broker
    container_name: kafka-broker
    depends_on:
        - zookeeper
    ports:
        - '9092:9092'
        - '9093:9093'
        - '9094:9094'
        - '9095:9095'
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
        KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
        KAFKA_SSL_CLIENT_AUTH: "requested"
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,EX_PLAINTEXT://localhost:9092,EX_SASL_PLAINTEXT://localhost:9093,EX_SSL://localhost:9094,EX_SASL_SSL://localhost:9095
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EX_PLAINTEXT:PLAINTEXT,EX_SASL_PLAINTEXT:SASL_PLAINTEXT,EX_SSL:SSL,EX_SASL_SSL:SASL_SSL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
        KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
        KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
        KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker.truststore.jks
        KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
        KAFKA_OPTS: '-Djava.security.auth.login.config=/opt/confluentinc/kafka/config/kafka_server_jaas.conf'
    volumes:
        - ./kafka-setup/secrets/trustoresandkeystores/broker_keystore_creds:/etc/kafka/secrets/broker_keystore_creds
        - ./kafka-setup/secrets/trustoresandkeystores/broker_sslkey_creds:/etc/kafka/secrets/broker_sslkey_creds
        - ./kafka-setup/secrets/trustoresandkeystores/broker_truststore_creds:/etc/kafka/secrets/broker_truststore_creds
        - ./kafka-setup/secrets/trustoresandkeystores/kafka.broker.keystore.jks:/etc/kafka/secrets/kafka.broker.keystore.jks
        - ./kafka-setup/secrets/trustoresandkeystores/kafka.broker.truststore.jks:/etc/kafka/secrets/kafka.broker.truststore.jks
        - ./kafka-setup/configs/kafka_server_jaas.conf:/opt/confluentinc/kafka/config/kafka_server_jaas.conf
