version: '2'

services:
  mysql:
    image: 'mysql:8-oracle'
    container_name: mysql-server
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MUSIC_STORE
      - MYSQL_USER=local_user
      - MYSQL_PASSWORD=password
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"
    network_mode: "host"
